@startuml
class Model.Core.SimulationManager {
- {static} SimulationManager instance
- int currentCapacity
- int currentCount
- double[] powerConsumptions
- double[] waterConsumptions
- double[] foodConsumptions
- double[] taxRevenues
- double[] maintenanceCosts
- boolean[] isOperational
- BaseBuilding[] buildingRefs
- ZoneType[] zoneTypes
- double[] happinessLevels
- <<Create>> SimulationManager()
+ {static} SimulationManager getInstance()
- void initArrays(int)
- void ensureCapacity()
+ void registerBuilding(BaseBuilding)
+ void updateBuildingData(BaseBuilding)
+ void removeBuilding(int)
+ void update()
+ boolean getIsOperational(int)
+ void setIsOperational(int,boolean)
+ BaseBuilding[] getBuildingRefs()
+ int getCurrentCount()
}


@enduml