@startuml
class Model.Building.Social.PublicUtility.PublicLibrary {
}
class Model.Building.Infrastructure.PowerGrid.CoalPowerPlant {
}
class Model.Building.Government.TaxOffice {
}
class Model.Building.Social.PublicSafety.MilitaryBase {
}
class Model.Building.Government.CityHall {
}
class Model.Building.Infrastructure.FoodSupply.LivestockFarm {
}
class Model.Building.Transportation.BusStation {
}
class Model.Building.Infrastructure.WasteManagement.Cemetery {
}
class Model.Building.Wellness.Gymnasium {
}
class Model.Building.Infrastructure.FoodSupply.GrainFarm {
}
class Model.Building.Transportation.TrainStation {
}
class Model.Building.Government.CentralBank {
}
class Model.Building.Infrastructure.PowerGrid.NuclearPlant {
}
class Model.Building.Wellness.PublicHospital {
}
class Model.Building.Infrastructure.WaterSupply.WaterPumpingStation {
}
class Model.Building.Social.PublicUtility.Temple {
}
class Model.Building.Social.PublicSafety.FireStation {
}
class Model.Building.Social.Education.VocationalCollege {
}
class Model.Building.Infrastructure.FoodSupply.VegetableFarm {
}
class Model.Building.Social.Education.University {
}
abstract class Model.Building.BaseBuilding {
# BuildingData stats
# int x
# int y
- ZoneType zoneType
# boolean isConnected
# int dataIndex
+ <<Create>> BaseBuilding(String,int,int)
+ void onTick(long)
# {abstract}void performIndividualDuty(long)
+ void onPlaced()
+ void onDestroyed()
+ void OnSelected()
+ void OnDeselected()
+ String getInfoSummary()
+ void onHoverEnter()
+ void onHoverExit()
+ void OnDestroy()
+ double getRefundAmount()
+ boolean isConnected()
+ void setConnectionStatus()
+ BuildingData getStats()
+ int getDataIndex()
+ void setDataIndex(int)
+ ZoneType getZoneType()
+ void setZoneType(ZoneType)
}


class Model.Building.Social.PublicUtility.Stadium {
}
class Model.Building.Government.PostOffice {
}
class Model.Building.Social.Education.HighSchool {
}
class Model.Building.Infrastructure.PowerGrid.SolarPanelPlant {
}
class Model.Building.Wellness.ElderyCare {
}
class Model.Building.Infrastructure.WaterSupply.WaterTower {
}
class Model.Building.Infrastructure.FoodSupply.FoodWarehouse {
}
class Model.Building.Wellness.MedicalClinic {
}
class Model.Building.Social.Education.ElementarySchool {
}
class Model.Building.Government.Courthouse {
}
class Model.Building.Wellness.Nursery {
}
class Model.Building.Infrastructure.WasteManagement.SewageTreatment {
}
class Model.Building.Social.PublicSafety.PoliceStation {
}
class Model.Building.Social.PublicUtility.PublicPark {
}
class Model.Building.Infrastructure.WasteManagement.WasteLandfill {
}
class Model.Building.Social.PublicUtility.Museum {
}


Model.Interfaces.Interaction.Tickable <|.. Model.Building.BaseBuilding
Model.Interfaces.Economy.RequirementChecker <|.. Model.Building.BaseBuilding
Model.Interfaces.Interaction.Clickable <|.. Model.Building.BaseBuilding
Model.Interfaces.Interaction.Hoverable <|.. Model.Building.BaseBuilding
Model.Interfaces.Interaction.Destructible <|.. Model.Building.BaseBuilding
Model.Interfaces.ResourceManage.Connectable <|.. Model.Building.BaseBuilding
@enduml