@startuml
interface Model.Interfaces.ResourceManage.WasteProcessor {
~ double getWasteCapacity()
~ void processWaste(double)
}

interface Model.Interfaces.BuffManage.HappinessProvider {
~ double getHappinessBonus()
}

interface Model.Interfaces.Economy.Housing {
~ int getMaxResidents()
~ int getCurrentResidents()
}

interface Model.Interfaces.BuffManage.HealthProvider {
~ double getHealthBonus()
~ double getServiceRadius()
}

interface Model.Interfaces.ResourceManage.PowerConsumer {
~ double getRequiredPower()
~ void setPowerStatus(boolean)
}

interface Model.Interfaces.ResourceManage.WasteGenerator {
~ double getWasteProductionRate()
}

interface Model.Interfaces.BuffManage.Pollutable {
~ double getPollutionIntensity()
~ double getPollutionRadius()
}

interface Model.Interfaces.AdvanceFeature.Transporter {
~ double getEfficiencyBoost()
}

interface Model.Interfaces.BuffManage.EduProvider {
~ double getEducationLevel()
~ double getServiceRadius()
}

interface Model.Interfaces.ResourceManage.PowerProducer {
~ double getPowerOutput()
~ void isFuelAvailable()
}

interface Model.Interfaces.ResourceManage.WaterConsumer {
~ double getRequiredWater()
~ void setWaterStatus(boolean)
}

interface Model.Interfaces.Interaction.Upgradable {
~ boolean canUpgrade()
~ void upgrade()
~ double getUpgradeCost()
}

interface Model.Interfaces.Interaction.Clickable {
~ void OnSelected()
~ void OnDeselected()
~ String getInfoSummary()
}

interface Model.Interfaces.Economy.Employing {
~ int getRequiredWorkers()
~ int getCurrentWorkers()
~ void updateWorkerCount()
}

interface Model.Interfaces.Interaction.Tickable {
~ void onTick(long)
}

interface Model.Interfaces.AdvanceFeature.Storage {
~ double getMaxCapacity()
~ double getCurrentCapacity()
~ void addResource(double)
}

interface Model.Interfaces.ResourceManage.WaterProducer {
~ double getWaterOutput()
}

interface Model.Interfaces.Interaction.Destructible {
~ void OnDestroy()
~ double getRefundAmount()
}

interface Model.Interfaces.Economy.Taxable {
~ double calculateTax()
~ void setTaxRate(double)
}

interface Model.Interfaces.AdvanceFeature.Beautifier {
~ double getTourismAttraction()
}

interface Model.Interfaces.BuffManage.SafetyProvider {
~ double getCrimeReduction()
}

@enduml